version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: trustbond_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@13579#2468
      POSTGRES_DB: trustbond
    volumes:
      - trustbond_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trustbond"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: trustbond_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - trustbond_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  trustbond_pgdata:
  trustbond_redis:
